### ISSUE TITLE
Save custom color sets

### ISSUE THREAD

**Issue by ceriath** [chatty/chatty#101]
Hello,

lately i wanted to experiment a bit with the different different colors, but the only thing, we can currently restore are the three default sets. A possibility to save own color sets would be awesome :)

**Comment by topster21** [comment]
I decided to take a jab at this (see [my branch](https://github.com/topster21/chatty/tree/CustomColorPreset)) and it is working as requested, but I am currently writing to the settings file directly ([example](https://github.com/topster21/chatty/blob/CustomColorPreset/src/chatty/gui/components/settings/ColorSettings.java#L199)) and I am not sure that is the right way.  Any input @tduva ?

**Comment by tduva** [comment]
Sorry for not answering earlier. Since I needed Color Presets for the new Notification System that can just take a number of ColorSetting objects without need for a setting name (the colors for the Notifications are stored in an object, not a dedicated setting), I created a more [generalized version](https://github.com/chatty/chatty/blob/master/src/chatty/gui/components/settings/ColorTemplates.java). I'll probably adapt that for the Colors settings. The only downside is that the ColorSetting objects aren't associated by a name, just the order they are added in, but I think that's acceptable, just need to keep that in mind if stuff is changed.
