### ISSUE TITLE
[feature request] Livestreamer/Streamlink intergration

### ISSUE THREAD

**Issue by craftwar** [chatty/chatty#148]
First, livestreamer should be renamed to new project name streamlink or user may get wrong program.

I wanna watch twitch in 720 (quality 720p or 720p60) but I can't  set this in context menu.
In command line, I can give "720p, 720p60" in quality option to streamlink.

from steamlink doc
Fallback streams can be specified by using a comma-separated list:
"720p,480p,best"

**Comment by h1z1** [comment]
Why?  Livestreamer is still a thing.  Regarding the options it's easy to wrap in a script.

**Comment by craftwar** [comment]
livestream project is stopped. Streamlink continues. They are basically the same in usage. Clear why we should replace it.

I think modifying Chatty makes this available to more people is better than writing script for personal usage. If tduva is not intended to add this, I will try make a PR when I have time.

**Comment by h1z1** [comment]
A bit pedantic but OK, great.   Hope I don't wake up one day to find the dependency I know, suddenly not there "just because".   Chatty doesn't really care what application you use, nor should it.

For what it's worth I ran into this same thing with the twitch official stream.  It wouldn't take "best" or "source".   On a couple other streams those options didn't reflect the proper quality either, sometimes dropping to mobile.  It's not a problem with Chatty or Livestreamer it's Twitch.   Modifying the already existing base command line setting in chatty made sense.

**Comment by craftwar** [comment]
Think about what a new user encounters when he tries to use Livestreamer. Livestreamer doesn't work to twitch stream without some fixes. But streamlink is fine, you don't need do anything.

BTW, I fix qualities parsing only. No touch about "Livestreamer" name cause there is opposite opinion.

**Comment by tduva** [comment]
I'm not sure I want to change the name everywhere, it already mentions Streamlink in the help though. I guess I can make that info a bit more prominent, that way people can decide themselves what they want to use. As long as streamlink doesn't change it's CLI interface too much it should work without any additional changes.

Can someone link the docs about the fallback stream qualities? I couldn't find it.

**Comment by h1z1** [comment]
@craftwar Livestreamer works fine though.  The problem is with Twitch.

@tduva only real place is --help.  You can specify quite  a bit of logic re what streams to try.   If you mean from twitch themselves, I'd think livestreamer is a bit of a thorn.  The fallback they do is not documented, it's not like an adaptive bitrate or anything (there's only one source in the playlist).

**Comment by craftwar** [comment]
@h1z1 
In my memory, I spent a lot of time in google to find out passing an  extra argument to make livestreamer work in twitch. I am not sure if twitch changes this. I am using streamlink now.

@tduva 
http://livestreamer.readthedocs.io/cli.html
[STREAM]

    Stream to play.

    Use “best” or “worst” for highest or lowest quality available.

    Fallback streams can be specified by using a comma-separated list:

    "720p,480p,best"

    If no stream is specified and --default-stream is not used then a list of available streams will be printed.

**Comment by tduva** [comment]
@craftwar Thanks.

I updated the help to make Streamlink more prominent and add some info about the new `{ }` syntax added in https://github.com/chatty/chatty/pull/152. I'll also add Streamlink to the feature list on the main page. This should be enough for people to know about it and decide what to use.
