### ISSUE TITLE
AbstractMethodError when logging Exception

### ISSUE THREAD

**Issue by chatty** [chatty/chatty#16]
There has been an `AbstractMethodError` when using `Throwable.printStackTrace` for some users for quite a while now. It is unclear as to how that can even happen, because a thrown exception (to my understanding) shouldn't be abstract. Because of this there is little information as to what causes the error, but it appears to be related to the GUI.

It appears to only happen on Java 8, although that may be because it's the current version and most people use it. It seems to happen on different OS (at least on Windows 7/8.1, Linux, OSX).

```
Exception java.lang.AbstractMethodError: java.lang.Throwable.printStackTrace(Ljava/io/PrintWriter;)V
    occured during logging of uncaught exception: java.lang.ArrayIndexOutOfBoundsException [Thread[AWT-EventQueue-0,6,main]]
```

Any suggestions or help would be appreciated.

**Comment by night** [comment]
Since the error occurs outside your code, it might just be because of differing runtime version versus compiled Java version. I'd guess this to be a Java bug, not really one of your own.

Obviously the "fix" to this problem would be to fix whatever array index if out of bounds, but without a stack trace I guess that's less than helpful.

**Comment by MeFisto94** [comment]
To me this sounds like "printStackTrace" would be an AbstractMethod (i.e. not implemented by the runtime). Maybe some openSource implementation on some linux distributions don't support it accidentally? Or did this also happen on Windows?

You can, however implement your own method for that by iterating. Throwable has some kind of stacktrace you have to iterate over. That would workaround that issue to at least track the error down.

**Comment by Azzurite** [comment]
How do you build the application when creating releases? It's probably a mismatch between linked classes.

**Comment by tduva** [comment]
I build it in Netbeans by clicking on "Clean and Build".

**Comment by Azzurite** [comment]
Could you please provide the ANT script you created?

**Comment by Azzurite** [comment]
Also, it's probably a bad idea to [catch Throwable](http://stackoverflow.com/questions/6083248/is-it-a-bad-practice-to-catch-throwable) in ErrorHandler.java.
If the AbstractMethodError would not be catched it would probably help debug the problem.

**Comment by tduva** [comment]
I'm not sure how that would give me any more information about the error. The UncaughtExceptionHandler is already the last resort. It informs the user about an error that might require the program to close and logs it to the debug file. So it's not like an error goes unnoticed because of that.

Because e.printStackTrace() on the Exception failed with an AbstractMethodError (and I think NullPointerExceptions), I added the catch Throwable in an attempt to log any useful information about the original error, which is the same as in the first post:

    10:50:44 Unhandled Exception:
    Exception java.lang.AbstractMethodError: java.lang.Throwable.printStackTrace(Ljava/io/PrintWriter;)V
        occured during logging of uncaught exception: java.lang.ArrayIndexOutOfBoundsException [Thread[AWT-EventQueue-0,6,main]]

Before it was something like this over an over again, which also could freeze the GUI, because of course an Exception in the ErrorHandler is also caught again by the ErrorHandler:

    15:48:39 Unhandled Exception:
    java.lang.AbstractMethodError: java.lang.Throwable.getStackTrace()[Ljava/lang/StackTraceElement;
        at chatty.ErrorHandler.uncaughtException(ErrorHandler.java:30)
        at java.lang.ThreadGroup.uncaughtException(Unknown Source)
        at java.lang.ThreadGroup.uncaughtException(Unknown Source)
        at java.awt.EventDispatchThread.processException(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

    15:48:39 Unhandled Exception:
    java.lang.NullPointerException
        at chatty.ErrorHandler.uncaughtException(ErrorHandler.java:33)
        at java.lang.ThreadGroup.uncaughtException(Unknown Source)
        at java.lang.ThreadGroup.uncaughtException(Unknown Source)
        at java.awt.EventDispatchThread.processException(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

I tried all sorts of things to get some information out of the original Exception, but even `toString()` was abstract as far as I can remember.

I also tried to compile the latest beta with Java 8 instead of Java 7 as before (because it seemed to occur mainly on Java 8), but I still had the error occur for people. Of course I'm not getting the error, so it's even harder to test stuff.

**Comment by Azzurite** [comment]
Again, it probably has something to do with the build you're doing, linking with a class that is fine on your machine but having a different versions on other machines. It could also be a problem in one of the libraries.
Could you please post your build script somewhere for me to look at?

**Comment by Azzurite** [comment]
Another idea would be, when an error occurs during the custom exception logging (like it happens here) to throw the **original** exception (the `e` in `void uncaughtException(Thread t, Throwable e)`) and let the JVM *itself* log it to stderr. If the JVM itself crashes on logging this exception, this would probably mean that there's a bug in the JVM. If the JVM does not crash, there's probably a bug somewhere in your build process or used libraries.
The second case is more likely, so it would be nice if I could take a look at your build script.

**Comment by tduva** [comment]
It's not possible to throw an exception in the `uncaughtException` method. I would have to add a `throws` to the method, but that means it doesn't override the method of the `UncaughtExceptionHandler` anymore.

I didn't make a build script, the IDE does all the building for me.

**Comment by tduva** [comment]
I haven't encountered this for a while, it may have been resolved by newer Java versions.
