### ISSUE TITLE
[Request] Add image to Tray notifications on Windows

### ISSUE THREAD

**Issue by stevek123** [chatty/chatty#169]
Right now, Windows 10 shows a blue "i" when notifications happen. I think it would be great, if it showed for example the streamer's avatar, or at least the chatty icon (and maybe also override the "Java(TM) Platform SE binary” name if it's possible).

**Comment by tduva** [comment]
I don't think that is possible with the API Java provides. Why are you using the Tray Notifications instead of the Chatty Notifications?

**Comment by stevek123** [comment]
I like the native experience, but yes, I can always go back to the built in one.

I've found these, maybe this helps you?
https://stackoverflow.com/questions/34866072/blank-icon-in-windows-10-notification
https://stackoverflow.com/questions/36883449/trayicon-notification-balloon-is-not-working-with-windows-10

https://stackoverflow.com/questions/5487615/changing-the-jframe-title

**Comment by tduva** [comment]
I'm already setting an image, but I didn't think that it was supposed to show in the notification itself as well, just for the tray icon itself. Changing the notification type from INFO to NONE doesn't show the image for me either on Windows 7 (none in fact, not even the question mark), but maybe it does show it on Windows 10, I don't know.

**Comment by tduva** [comment]
I changed the Tray Notification type in [v0.8.7b2](https://github.com/chatty/chatty/releases/tag/v0.8.7b2), could you test if an image shows up now?

**Comment by stevek123** [comment]
It shows up now as expected :) Thanks for fixing it!

**Comment by tduva** [comment]
So I'm guessing changing the notification type from INFO to NONE did it, since NONE doesn't show an icon by default, so it shows the image of the Tray Icon.

Unfortunately on Windows 7 at least it now doesn't show any icon. Or rather I'm not sure if it's unfortunate, people might find it fine without an icon as well, if I can't show a more appropriate one anyway. I guess I'll wait and see if anyone complains about it.
