### ISSUE TITLE
[Bug] Crash on switching tab

### ISSUE THREAD

**Issue by Bene-GG** [chatty/chatty#172]
I'm experiencing this behaviour since some time now, after some time when I switch to a different channel (tab), Chatty just closes without any further notice.

This is one of the logs after a crash, please tell me if you need any further info.

hs_err_pid10548.log 01.08.2017 22:03: https://hastebin.com/anunoxikoq.tex

**Comment by tduva** [comment]
Since Java itself crashed, this hints to some kind of bug in the JRE or an incompatibility of some sorts, probably graphics related. It looks kind of similiar to [this first issue](http://chatty.github.io/help/help-issues.html). Maybe you could try the workaround of adding the `-Dsun.awt.nopixfmt=true` commandline parameter.

**Comment by Bene-GG** [comment]
Seems to work like a charm now, thanks for the help!
