### ISSUE TITLE
Option to disable highlighting messages for emotes

### ISSUE THREAD

**Issue by JackyyTV** [chatty/chatty#174]
So as you know, my name is Jacky (obviously), and I've got `jacky` as a highlight keyword, like this:
![](https://i.gyazo.com/7abe8ec8900b4f240619e126dae4e148.png)
So of course, it'll highlight in chat like this:
![](https://i.gyazo.com/1c7fe03e5e82116fc7635d451cd07188.png)
But apparently, there's an emote called `jackYUP`, which apparently highlights for me because of the `jackY` part, like this:
![](https://i.gyazo.com/cb1c2c39d2363a6fcbe685d451e5eb59.png)
That is getting quite annoying for me as it's highlighting messages that arent't even mentioning my name. Is it possible to have an option to disable highlighting for emotes? Thank you.

**Comment by tduva** [comment]
I'm not sure this would be very easy, since the Highlights system is not aware of where emotes are.

You can make the pattern `w:jacky` to only match words, but that wouldn't match `JackyBot` if that's what you want. You could prevent matching that emote in particular by using `re:(?i).*jacky(?!UP).*`, which matches `jacky` in anything (and any case), except when it's followed by `UP`.

**Comment by Jacky1356400** [comment]
Ah I see, guess I will have to use Regex for now then (wasn't really what I wanted to do but looks like Regex it is afaik).

**Comment by Exavior** [comment]
This would actually be an easy fix, since emotes are limited.  All we need is the ability to blacklist terms.  Most streamer's alert on their own username, and most emotes contain your username.  This is making my alerts go crazy.  So if my name is "foo" and my alerts are "fooRaid" or "fooHi" all I need is the ability to blacklist "fooRaid" and "fooHi" 

There is an "ignore" option, but that hides all messages containing the key value, rather than just omitting them from alerts.

Super surprised this has not been addressed yet.

**Comment by tduva** [comment]
It's a bit more complicated than that. What if someone writes "Hi foo fooHi"? If "fooHi" is on the blacklist, is it supposed to not highlight that message because it contains "fooHi", even though it also contains your name? Or just when "fooHi" was the word (whatever you count as a word) that caused the match in the first place? In that case matching gets a lot more complicated, because it can't just check for a match, but also has to check for each match if it is part of a blacklisted word, and if so maybe keep searching for one that isn't. Not impossible to do, but it needs to be well defined what the blacklist actually does.

If you just want to match the word "foo", but not words containing it, when you can just use `w:foo`. The "Highlight own name" option uses that as well.

**Comment by Exavior** [comment]
Think of the "blacklist" as an exclude list that prevents those terms form triggering the alert, not stopping the alert from happening.  

If you said "Hello foo fooHi" and "fooHi" were on the blacklist, it would still highlight because the "foo" in "Hello foo" would trigger the alert.   If word contains "foo" and word is not in blacklist, show alert.

It just ignores the blacklisted terms as triggers.  Would be very simple to add and would save a lot of headaches, and prevent users (who not many not be regular expression savvy) form having to write long expressions to exclude all their channel emotes.

**Comment by tduva** [comment]
Can you tell me why `w:foo` wouldn't work for you?

**Comment by Exavior** [comment]
Because names (or other terms you may wish to highlight on) are not always wrapped with spaces or punctuation, and there is **value** to users in matching within the content of a longer string without having to go the regular expression route.  (making things user friendly is important, and there are already enough UI/UX concerns here) 

This is not novel functionality.  Standard twitch chat/BTTV highlighting exclude emotes, so adding workarounds and regular expressions is just putting a bandaid on (or ignoring) what may not technically be a bug, but is at the very least a functional oversight.   Adding an ignore/blacklist/exclusion list is still a bit of a workaround, but if no other solutions are bing proposed, and omitting emotes form matching is overly complicated, it may at least be an improvement.

I'm of the mindset to always make things better, and making chatty better would be a good thing.  Functional parity with its counterparts is better.  Lets go for better.

**Comment by tduva** [comment]
I'm not arguing a blacklist would be a bad thing to have, the issue of unwanted matches came up before. I was just trying to understand why the `w:` prefix wouldn't work for your example, which seems the most common use case. It would have been an immediate fix for that situation. But I guess you weren't actually just having the issue of the example.

Being able to highlight emotes is certainly no bug, because you may want to highlight or ignore on emotes. Optionally disabling it would require quite a few changes. Unfortunately I don't have time for this right now. There are just too many good ideas to implement sometimes.

**Comment by tduva** [comment]
I currently don't have time to implement this, but I just wanted to leave some thoughts about it here.

Just allowing words on the blacklist seems a bit limited (if you interpret a word like in regex). For example if you want to prevent "ROM Hack" from triggering on the highlight term "ROM".

Maybe just look for any blacklist matches, save the indices, and then if one of the blacklist matches spans an entire highlight match (or more) it would prevent it.

For example "jacky" would match "jackY" (14-19) in "Doing awesome jackYUP", and the blacklist item "jackYUP" would match "jackYUP" (14-21). Since 14-19 is inside 14-21 it would ignore that match. Same for "ROM" (12-15) and "ROM Hack" (12-20) in "I like this ROM Hack :)", but not for "PROM" (12-16) and "ROM Hack" (13-21) in "I like this PROM Hack :)" (ok, I have no idea what a PROM Hack is, but it's just an example ;)).

Anyone got an example where this *doesn't* work? I may have overlooked something.

That requires a few changes:

* Using regex under the hood instead of e.g. `String.contains()` and the like to be able to easier get the match indices (shouldn't be an issue to get the same behaviour using `Pattern.quote()`).
* For anything using the "re:" prefix it wouldn't work at all, since it always tries to match the entire string (`Matcher.matches()`), so you have to use `.*` wildcards if you want to find part of the message. That means that it always shows the entire string as a match, not what the user actually intended. But that's more advanced stuff anyway, and you can use `re*:` now to match part of a string, which works with `Matcher.find()`.
* Each `HighlightItem` would potentially have to look for more than one match, instead of just the first one, because some may be blacklisted and others not.
* Could either first look for all blacklist matches and give the `HighlightItem` the indices to ignore, or give the `HighlightItem` the blacklist `Pattern` objects to only check in case of a match.
