### ISSUE TITLE
Issue with the Standalone version of Chatty

### ISSUE THREAD

**Issue by Zero3K** [chatty/chatty#178]
It takes over a minute to load under Windows 7 that is on a SSD. Is there any way to make it load quicker or not:?

**Comment by tduva** [comment]
That's weird, it starts in under 10 seconds for me. Can you check the debug log (Extra - Debug window) after starting it and find out by the timestamps when Chatty is actually executed by the JVM compared to when you start it (first timestamp vs. time you double-click on the program) or if any of the steps in the Chatty startup take really long.

**Comment by Zero3K** [comment]
Here's the debug log. It seems to be because of it deleting old images from its cache.

[debug.zip](https://github.com/chatty/chatty/files/1272550/debug.zip)

**Comment by tduva** [comment]
That's weird, because it shouldn't take over a minute to delete some files and it also shouldn't do that every single time, because there won't be old files on every start. Maybe it somehow failed to delete the files, even though Java said it did? `ImageCache: Deleted 2807/2807 old files` means it thinks it succeeded deleting all old files.

Can you tell me if Chatty wrote new files into the cache again (which it should) and whether `/clearimagecache` in Chatty successfully deletes them?
