### ISSUE TITLE
[Request] Font configuration for input/userlist

### ISSUE THREAD

**Issue by JeGr** [chatty/chatty#219]
Hi,

thanks for adding the possibility to change the font setting for the input field and userlist. Would it be possible though to add it like the normal chat font setting? The fixation on "Dialog" or "Monospace" and the bold variants and the predefined sizes are nice to start with, but for using it as a Moderator tool in channels with BIG userlists I find it still lacking configuration options. I for myself would like to set it to SegoeUI on Windows to give the whole Window/App a more native feeling and set it below 12pt size so to have a bigger userlist available.

Thanks for your great effort in making (one of the greates / the best) tool for Twitch Chat cross platform!

Greets,
-jens

**Comment by tduva** [comment]
The Settings Dialog only offers those two fonts due to a Java bug that can break the fallback fonts if any other than the logical fonts are used in the input box. I don't know if that still applies with recent versions, but that's why it is this way. If you really want another font you can always use [setting commands](http://chatty.github.io/help/help-setting_commands.html).

For example: `/set userlistFont Arial 10` (anything understood by [Font.decode()](https://docs.oracle.com/javase/7/docs/api/java/awt/Font.html#decode%28java.lang.String%29))

**Comment by JeGr** [comment]
Ah! Didn't know that, is that mentioned somewhere in the help docs?

**Comment by tduva** [comment]
I linked the setting commands help, which lists a lot of settings, although I don't think it had the userlistFont setting on it yet.
