### ISSUE TITLE
Whispers coming in, but not going back out

### ISSUE THREAD

**Issue by Fentist1x** [chatty/chatty#222]
I can receive whispers from anyone. I can respond in chatty, but the other person does not get the return whisper. i have to go back to the twitch site itself to whisper.  The whitelist only still doesnt work that i reported months ago. Whispers need to be looked at and updated so that they function as intended.

**Comment by tduva** [comment]
That sending whispers doesn't work is a very common problem with Whispers unfortunately. I'm not sure there is much I can do about that.

You can check that Chatty tries to send the Whisper via `Extra - Debug Window - Irc log` (tick `Irc log` at the bottom as well). You should see something like `PRIVMSG #<yourname> :/w <recipient> <message>`. If you do see that, but it still doesn't go through, then it's on Twitch's side.

**Comment by mucitrus** [comment]
This is very frustrating one of the purpose for me useing this program. 

I have tried open all ports, force to another, but I can just recieve whispers and not send them, but my friend can just do both. Need an fix for this since some work and some not, mine have NEVER worked so there must be a problem. Thanks for and cool program.
