### ISSUE TITLE
High CPU usage with Java 8 Update 161

### ISSUE THREAD

**Issue by tduva** [chatty/chatty#227]
I've gotten several reports that the latest Java update is causing high CPU usage, especially when Chatty is not doing much. This is with Chatty version 0.9 (at least what I tested with).

This is how I can sort of reproduce it: When I slightly move the window and then do nothing, sometimes the CPU usage constantly stays at 25% (while Chatty is basicially doing nothing, not even connected). It probably can also happen on it's own since I noticed it doing it yesterday after just leaving it for a while. When I click anything in the window, like opening a menu, the CPU usage goes back to normal again (mostly 0-1% when completely idle).

I've also noticed that when the CPU usage was high, the thread `AWT-EventQueue-0` would constantly run, and as soon as I clicked into Chatty both the CPU usage and the thread would go back to normal (as in, only run from time to time).

Unfortunately I haven't been able to find out more, so I don't know if it's something I can fix or workaround yet.

![high_cpu_usage](https://user-images.githubusercontent.com/5621113/35190751-8f9dfd10-fe69-11e7-950c-4c18388807fe.png)

**Comment by tduva** [comment]
I narrowed it down to the `JTextField` gaining focus when the window gains focus. For example if I run the following program:

```
public class JTextFieldTest {
    
    public static final void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame window = new JFrame("Test");
            window.setLocationByPlatform(true);
            window.add(new JButton("Button"), BorderLayout.CENTER);
            window.add(new JTextField(), BorderLayout.SOUTH);
            window.pack();
            window.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            window.setVisible(true);
        });
    }
    
}
```

* If the window gains focus while the button is focused, then it's ok. Even clicking into the input box afterwards it's fine.
* If the window gains focus while the cursor was in the input box before, the CPU usage gets constantly high. Clicking onto the button fixes it. Clicking back into the input box is ok then.

So it only seems to be an issue when the `JTextField` is the first thing to gain focus.

Since even this simple program has this issue, it's obviously a Java bug introduced with that update. Hopefully they'll fix it.

**Comment by MentalFS** [comment]
I can't find anything at [the Java Bug Database](https://bugs.java.com), so they might not be aware. The search functionality is quite limited though, maybe someone else can find it.

**Comment by tduva** [comment]
Someone already submitted that, but it's probably still under review.

**Comment by tduva** [comment]
Here is the bug now: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8195830

**Comment by tduva** [comment]
I've added a workaround in v0.9.1b1, I hope it works. It might still be better to use a different version though.

**Comment by MadMakz** [comment]
Still there with 0.9.1b1 :(

**Comment by Baerht** [comment]
the problem seem to get worse the more chat windows you have active

**Comment by wongjoel** [comment]
Bug is supposed to be fixed in 8u172

**Comment by Baerht** [comment]
surre we believe them

**Comment by Mitsuma** [comment]
So this problem still persists? I suppose that java update 172 isn't out yet because I'm still running u161.
Chatty is always taking over a two threads on my 12 threads when it just runs for a while and does nothing.
One core gets almost maxed, the other has a little higher usage.

**Comment by wongjoel** [comment]
Given that the bug has been tracked down to being particular to Java 8u161 on Windows, I would suggest it might be worth trying to work around it by either trying running it on Java 9 instead, or running the early access build of 8u172.

**Comment by tduva** [comment]
I don't know of any way of fixing this myself and the workaround I implemented in the beta only seems to work for some cases.

I can only recommend using a Java version other than 8u161/162, either by using the Standalone Version (which still has 8u151 bundled) or installing a different one yourself, as recommended by wongjoel.

**Comment by lewisje** [comment]
I'll just say that the problem still showed up while using Java 9.0.4 with the previous version of Chatty; I just got the new version and I will test it with Java 10 (the direct successor to Java 9.0.4), and if the high CPU usage still happens, I'll switch to the version bundled with the older version of Java 8.

**Comment by h1z1** [comment]
Given exploits against the JVM itself do exist, upgrading to the latest version should be required or at least closely tracked.   Anything pre-January 2018 is vulnerable to Spectre and Meltdown too.   April 2018 has, I kid you not, 14 _new_  updates Oracle classifies as critical.  Granted they are webstart related which Chatty doesn't use, but still.

**Comment by tduva** [comment]
The standalone will be updated to 172 before the next release if it indeed doesn't have any major issues anymore.

You're right at pointing out though that the most critical Java security issues probably don't apply to the kind of program Chatty is, since a lot of them are about breaking out of a sandboxed environment. I'm also not quite sure if Spectre/Meltdown apply, doesn't that require some kind of untrusted code to run, like JavaScript in a browser? Basicially again, breaking out of a restricted environment in a way. But I'm certainly no expert on that topic and it's always a good idea to update (as long as the updates don't break stuff 💩).

**Comment by h1z1** [comment]
Buzzword Bingo indeed.  Kinda lost track of which Spectra/Meltdown variant was exploitable and where.  Meltdown is the more serious one, Intel won't even attempt to patch half their CPUs, Sepectra is Intel's spin to drag AMD into it.  One is a more general  attack on _any_ cache.  

At least one was via a browser though and that isn't even touching the latest round of them.  

Hardware aside, FWIW, seems OK on 10.0.1.

**Comment by tduva** [comment]
Seems to work in 8u181 as well, probably easier to install for the normal user than 8u172.

**Comment by lewisje** [comment]
Similarly, there's no problem with 8u192, but there is a potential problem on the horizon: The last publicly available installer for the 32-bit JRE will be released in January and it will be for Java 8 (probably "Java 8u201" and "Java 8u202"); I don't know whether Oracle will pull those final installers the way they did for Java 9 and 10, but going forward, you might want to make sure Chatty works in Java 11, which is 64-bit only.

What's worse is that Oracle [isn't even providing JRE installers for Java 11](https://sdtimes.com/java/java-11-is-now-available/) (only JDK, but with a private JRE), but I learned in [this Reddit thread](https://www.reddit.com/r/java/comments/9qhhun/explaining_java_11_installation_to_beginners/e89f7k4/) about a project by Azul Systems to provide a pre-built JDK distribution, based on OpenJDK, known as [Zulu](https://www.azul.com/downloads/zulu/), and also about [AdoptOpenJDK](https://adoptopenjdk.net/), which provides (through the "Installation" link) downloadable pre-built JREs (this is more in case you want to keep offering a stand-alone JAR and telling people where to get a JRE, although it isn't as nice as being able to install one).

The aforementioned JREs (whether through Zulu, through AdoptOpenJDK, or through the Oracle JDK 11) do not work with Chatty as distributed, and that's probably because they're all 64-bit; even the 64-bit JRE 8u192 doesn't work, and it fails in the same way (Failed to locate JNI_CreateJavaVM).

I'll soon look into whether Chatty compiles on 64-bit Java 11, but considering someone in another issue said it would compile on JDK 10, which is also 64-bit only, I suspect it will; also, FWIW, Chatty does work with the 32-bit Zulu build of JDK 10 (no 32-bit Zulu build of JDK 11 yet, possibly ever), but the UI elements are sized better in JRE 8.

**Comment by tduva** [comment]
Thanks, this is all pretty confusing. One alternative for javapackager I've seen mentioned is jlink, but I haven't looked into it yet. I'm not sure why Chatty wouldn't run on 64bit JRE in particular, since many people have been using it on 64bit for ages (hence the 64bit hotkey version), but maybe I'm misunderstanding. It's difficult to keep on top of things while also concentrating on developing, so I appreciate any information that helps to keep Chatty. Although it might be better to open a new issue immediately, since this seems kind of off-topic.

**Comment by suryababy** [comment]
Good article. A complete solution for Troubleshoot JVM crashes, slowdowns, memory leaks, freezes, CPU Spikes <a ref="http://fastthread.io/">Thread Dump Analyzer</a>
