### ISSUE TITLE
Mute User

### ISSUE THREAD

**Issue by mtcjayne** [chatty/chatty#251]
Is there a way to mute notifications from a specific user? I'd like to not get notifications from a bot account.

**Comment by tduva** [comment]
There's several ways:

* If simply not highlighting the user is an option, then:
  * You can add the user to the "Users to never highlight" list
  * Or you can add a `cat:nohl` in front of the individual Highlight list item, then add users you don't want highlighted to the `nohl` Addressbook category
* If you just don't want the Highlight notification to pop up (but still have the message highlighted), then:
  * You can add `cat:nohl` to the `Match` field of the Highlights-Notification item, then add users you don't want highlighted to the `nohl` Addressbook category

If you want to do the same for all known bots (that have the bot badge in Chatty), then you can use `!status:r` instead of `cat:nohl`. If it's not a known bot, then you can add it for yourself locally using the command `/add botNames <botname>` (you have to restart Chatty for it to take effect).
