### ISSUE TITLE
Twitch tag support

### ISSUE THREAD

**Issue by craftwar** [chatty/chatty#280]
https://blog.twitch.tv/introducing-tags-and-new-categories-33744ef7b04f

Community is removed.

**Comment by tduva** [comment]
I'll remove Communties from Chatty, but I can't really do anything about Tags until Twitch releases an API for it.

**Comment by DjRicko** [comment]
Make a workaround that just uses the http dashboard and cookies for login info and edit them that way.
Ofcause as a temporary measure untill a proper api is released.

**Comment by tduva** [comment]
I'm not sure how that is supposed to work. To use the GraphQL API you need an onsite token afaik, so there'd have to be a browser where people login into Twitch and Chatty somehow grabs the token or cookies and then makes the request. Not sure if that is even technicially possible, I don't know how long the token would be valid, I don't know if Twitch would be ok with it and it doesn't sound nice to begin with (including a browser, letting people login to Twitch, making some weird unsupported requests). If people have to login to the website anyway, they could just change the tags there without any dirty hacks. The only difference would be that there are no presets (I don't understand how Twitch doesn't have anything like that yet).

Since I have enough other stuff to work on for Chatty, I'll pass on this until they release an official API.

**Comment by tduva** [comment]
Stream Tags support is in the latest beta.
