### ISSUE TITLE
BTTV Personal Emotes

### ISSUE THREAD

**Issue by nyaarium** [chatty/chatty#282]
Chatty supports BTTV emotes, except for the "Personal emotes". Could we get that added?

**Comment by tduva** [comment]
I don't really know how they work and currently I don't have time to look into it, but in general I'm not opposed to it.

**Comment by JAYR4GE** [comment]
Just wanna bump that up again or is it in and im blind?

**Comment by Iku** [comment]
As of right now BTTV doesn't support personal emotes in their API.  I've opened up a feature request, for now, we can just hope night feels not lazy.

[https://github.com/night/BetterTTV/issues/3612](url)

**Comment by Iku** [comment]
After doing a bit of research, to make it simple you need to connect to the socket server via:
https://github.com/night/BetterTTV/blob/master/src/socket-client.js 

on message it parses the json response for the emote info. There is reconnect stuff, and some other methods. It's all pretty self contained

And it is then used here in BetterTTV:
https://github.com/night/BetterTTV/blob/master/src/modules/emotes/personal-emotes.js

You just need to connect to the server and handle how you deal with the messages. otherwise the process itself is pretty simple
