### ISSUE TITLE
[Request] Android and IOS version

### ISSUE THREAD

**Issue by Esummoner** [chatty/chatty#286]
Would love to see a version for phone or tablets.
This way we can wacht twitch full screen on TV or Monitors and still easily chat while relaxing on the couch with our tablet for chatting.

**Comment by tduva** [comment]
Chatty can't just be ported to Android or iOS, so it would require writing a completely new App (or two even), which I don't have the time for. At that point it doesn't have much to do with Chatty anymore anyway, except maybe for branding. If someone else wants to start something like that they'd probably just pick a different name. Since I don't use mobile very often I don't know what Apps might already exist.
