### ISSUE TITLE
"latest" tag for last stable version available

### ISSUE THREAD

**Issue by grolongo** [chatty/chatty#287]
Hi tduva,

Thanks for your good work,

Would it be possible to tag the last stable versions with "latest" instead of the version number for url download links?

I'm using scripts to automate installs of different packages on my machines and have to change the version number in those every time a new stable version is available.

Example, modify this:
https://github.com/chatty/chatty/releases/download/v0.9.2/Chatty_0.9.2_win_standalone_setup.exe
to:
https://github.com/chatty/chatty/releases/download/latest/Chatty_latest_win_standalone_setup.exe

Thanks

**Comment by tduva** [comment]
It's not practical to change the tag of a release:

* There's no feature on GitHub to delete or move a tag, so it would have to be done in the local repository and then pushed, which is a bit weird (I'd rather not change tags in a repository unless I really need to).
* It would be impossible to link to the latest release not just as the latest release, but as a specific release, since the link would change later.
* Would "latest" be the latest full release or the latest beta? Two different "latest" tags would complicate things even more.

If you want to automatically get the latest version, you can use the [GitHub API](https://developer.github.com/v3/repos/releases/).
