### ISSUE TITLE
[Bug Report] Emotes for a renamed channel no longer show in "Channel" dialog

### ISSUE THREAD

**Issue by mikemar921** [chatty/chatty#300]
**Describe the bug**
A streamer in twitch recently changed their name.  When their name change went through, the Channel dialog for emotes no longer show the subscription based emoticons - they only show the BTTV emotes that are associated with the new account.

**To Reproduce**
Go to a streamer who has changed their name (for example, rawb, sharon, pause).
Open the Emote dialog box and select Channel.
BTTV emotes show as expected at the top.  However, the subscription based emotes no longer show up under the BTTV emotes.  The emotes for the channel do show in the My Emotes dialog.

**Expected behavior**
I would expect the subscription based emotes to be populated under the Channel dialog in addition to the emotes in the My Emotes dialog.

**Debug Log**
[debug_session.log](https://github.com/chatty/chatty/files/2711360/debug_session.log)

**Screenshots/Videos**
Current rawb Channel dialog emotes
https://gyazo.com/b57f5c2fffb6284e72b9a375dbabf60a
Current My Emotes dialog for rawb (original name was rurikar22)
https://gyazo.com/6d7fe57761184d6ee41d1c2a52cf0a6f

**Additional information (please complete the following information):**
- OS (e.g. Windows 7): Windows 10
- Chatty Version (e.g. v0.9.1 Standalone): Chatty_0.9.3-b5_hotkey_64bit
- Java Version (if not using Standalone): java version "1.8.0_171"
- When has the issue first occured (Chatty Version or timeframe): Noticed it for a long time, just never reported it.
- How often does the issue occur (everytime, sometimes): everytime

(*Tip:* Use `/appinfo` in Chatty to get some of this information.)

**Additional context**
I am not sure if this is a Twitch bug on how it is passing the data to you or not, so I at least wanted to write something up in the event it could be taken care of.

**Comment by tduva** [comment]
FFZ Emotes will show up when the channel owner goes to FFZ Website and log in again to update their name. I will soon change to the FFZ API that uses channel ids, but I haven't gotten around to it yet. Although you don't mention FFZ emotes anyway.

Twitch Emotes are a bit more complicated, because Twitch doesn't offer an API to associate the channel name with the emotesets, so I have to rely on a third-party API. That dataset is also really huge, impossible to load into Chatty, so I have to transform it first, which isn't done very often. So there's not really anything I can change here except update the data more often or use another third-party API that offers the same data (or hope for Twitch to add it to one of their APIs that we are actually allowed to use).

**Comment by mikemar921** [comment]
That makes sense (and appreciate the extra info for FFZ).  I had a feeling it was related to the information that is available to be obtained from twitch.

If I am understanding correctly, the next time that you compile/transform this list, it should fix itself (once the third party API realizes the channel name change), correct?

**Comment by tduva** [comment]
Yes, that is correct.

**Comment by mikemar921** [comment]
Thanks again, appreciate it (and all that you do for this app 😄 ).
