### ISSUE TITLE
Chatty uses too much memory

### ISSUE THREAD

**Issue by craftwar** [chatty/chatty#303]
KVirc (an irc client) uses about < 2xMB.
/appinfo output
Chatty Version 0.9.3 Hotkey [Memory] total: 184,320 used: 164,836 free: 19,483 max: 184,320
In task manger, Chatty uses about 10X ~200MB+

**Comment by tduva** [comment]
That seems like pretty normal memory usage. Without being too familiar with KVirc, there's probably a few differences that make Chatty have a higher memory usage:

* Java will always allocate more memory than it actually needs, so it doesn't have to clean up as often, reducing CPU load
* Java has to load a lot of stuff, such as their own GUI libraries, whereas native programs may use more stuff already provided by the OS directly
* Chatty probably has to handle a lot more data than a simple IRC client, due to Twitch specific features (such as Emotes, Badges, Stream Info and the necessary API requests) and other features such as storing everything any user has said

Some of these things can be improved, like it already has happened e.g. for the Emoticon data, which used to store info on *all* Twitch emoticons (which was fine a few years back, but today it wouldn't even be possible to parse the JSON from the API with 200MB RAM), whereas now it only requests the emotesets that are needed. However I don't think it would be possible to reach as low a memory usage as KVirc, it's just the nature of Java and doing many more things than an IRC client.
