### ISSUE TITLE
I dont understand how to set up multiple Chatty´s

### ISSUE THREAD

**Issue by DS1337** [chatty/chatty#322]
Hello together,

i rly dont get it, how to set up multiple instances of chatty...

I got 4 Twitch Accounts and I just want to start 4 times Chatty with 4 different settings.
But i dont understand, how to setup this correctly...

Is there a good Video for it?

> You can change the default settings directory by using the -cd commandline paramter, which changes the settings directory to the current working directory, meaning the settings are loaded and saved in the same location you specified as working directory.

Where? in cmd? in Chatty? In a special file?
there is nowhere written where to enter it?!

> You can also use the -d <dir> parameter to specify the directory directly. For example if you create two different shortcuts like this:

    javaw -jar "D:\Chatty\Chatty.jar" -d "D:\Chatty\settings1"
    javaw -jar "D:\Chatty\Chatty.jar" -d "D:\Chatty\settings2"

Where to type this?

> Of course you have to change D:\Chatty\Chatty.jar to where your Chatty.jar is actually located. You also need to first create the settings folders you specify.

i create 4 folders with the Chatty.jar in it, but then???

It was explained very complicated and it is not specified where I have to enter all this etc.

so again:
i want to have 4 Folders with Chatty with 4 different settings.

As an an example:

I downloaded Windows Standalone (.zip) and unzipped there:

C:\Chatty1
C:\Chatty2
C:\Chatty3
C:\Chatty4

Where do I type the commandline paramter, so that the settings are saved in the respective folder and then I just have to start Chatty.exe, so my settings were adopted?

And there are 4 different downloads. Which chatty version do I need for this?

> Download Windows Standalone (Installer)
Download Windows Standalone (.zip)
Download JAR-Version (Installer)
Download JAR-Version (.zip)

> If you're using the Windows Standalone, then simply run Chatty.exe instead:

    "D:\Chatty\Chatty.exe" -d "D:\Chatty\settings1"
    "D:\Chatty\Chatty.exe" -d "D:\Chatty\settings2"

This does not mean anything to me. what should I do with it?

If i do some copy of Chatty and starting chatty.exe, there is loading every time the last saved settings...

i dont see a command pompt in Chatty.exe to type "D:\Chatty\Chatty.exe" -d "D:\Chatty\settings1"?!?!

So what to do with this, and where?!?!?!
"D:\Chatty\Chatty.exe" -d "D:\Chatty\settings1"

Extrem confused guide, sry...

greetings :)

**Comment by lewisje** [comment]
All of those commands are meant to be typed in the Command Prompt; go to the Start Menu and type "Command" into the search bar and soon you should find the Command Prompt.

Also, you should have only one copy of the standalone Chatty, so re-name C:\Chatty1 to C:\Chatty, delete the other three folders, create the folders settings1, settings2, settings3, and settings4 inside C:\Chatty, and then enter these four commands into the Command Prompt (or make four shortcuts, edit each one to change its "location" to one of these commands, and then double-click each one):

    C:\Chatty\Chatty.exe -d C:\Chatty\settings1
    C:\Chatty\Chatty.exe -d C:\Chatty\settings2
    C:\Chatty\Chatty.exe -d C:\Chatty\settings3
    C:\Chatty\Chatty.exe -d C:\Chatty\settings4

You won't need quotation marks, because these paths don't have spaces inside, but use them anyway if you feel like it.
