### ISSUE TITLE
[Feature request] Delete (not just the user's last) message on context menu

### ISSUE THREAD

**Issue by tezJR** [chatty/chatty#324]
**Is your feature request related to a problem? Please describe.**
I can delete the last message in the user dialog, but no previous individual message.

**Describe the solution you'd like**
Like Automod Approve/Deny options on right-clicking the username on that message, add Delete Message as an option for any message we can delete.

**Describe alternatives you've considered**
Purging is always an option, but it'd be nice to be able to fully use this relatively new delete single message feature in Chatty.

**Comment by tduva** [comment]
If you click on a username in chat it opens the User Dialog in the context of that message, which is marked with a `>`. You can refer to that msg in custom commands, for example `Delete=/delete $$(msg-id)`, which you can add to either the "User Dialog Buttons" or "User Context Menu" setting on the "Commands" settings page (the User Dialog "Delete"-button should be added by default).

Note that you won't be able to test this with messages you sent yourself through Chatty, since Chatty won't know their message id.

**Comment by tezJR** [comment]
My bad. You're completely right. I always clicked on the last messages, never earlier ones. (D'oh) Thank you!
