### ISSUE TITLE
FFZ:AP Badge support

### ISSUE THREAD

**Issue by barbiehunter** [chatty/chatty#329]
Hi, I like using Chatty but it would be a little nice if you add Support for the FFZ:AP Support ( https://ffzap.com/ )Maybe you wanna do it, thx.
![image](https://user-images.githubusercontent.com/38357837/60356645-d3139000-99d1-11e9-901e-c959cf640b15.png)

**Comment by tduva** [comment]
FFZ:AP badges have been added.

**Comment by barbiehunter** [comment]
Are you sure? it doesn't show my FFZ:AP Supporter badge in Chatty. Must i write any command or clear cache via a command? 
![image](https://user-images.githubusercontent.com/38357837/73612531-dff20500-45ec-11ea-9f62-4cbf51f098d2.png)

**Comment by tduva** [comment]
You can try `/refresh badges`, although I think the issue is that the userid isn't contained in the `USERSTATE` message when joining a channel, so Chatty doesn't associate with the local user. It should work for received messages though (I've seen the badges of other users).

You can click on your own name to open the User Dialog so it loads the id, then it should work. Not really practical to do this every time you join a channel though. I'll release an update at some point that sets the id from the `GLOBALUSERSTATE`.

**Comment by barbiehunter** [comment]
Ok it worked with the `refresh badges` command after 2 trys, thx for the information/help
