### ISSUE TITLE
[Improve] Pride emotes

### ISSUE THREAD

**Issue by barbiehunter** [chatty/chatty#330]
![image](https://user-images.githubusercontent.com/38357837/60395620-83020e00-9b36-11e9-94fc-fc1902cf5a6b.png)
 Maybe just try to fix it, idk what the problem can be by this from Chatty

**Comment by tduva** [comment]
It's a bug in Twitch Chat that provides the wrong emotesets for these kinds of emotes. There is a Rest API endpoint that provides the emotes as well, but that is bugged in a similiar way, so I can't just get the emotesets from there and use the same process otherwise. It requires quite some changes to work around all that, which I haven't had time for yet.

**Comment by tduva** [comment]
These emotes should show up now providing your login has the correct access. What still won't work are emotes modified by channel points, since those simply aren't supported by the publicly acccessible API.
