### ISSUE TITLE
Support custom display with channel points

### ISSUE THREAD

**Issue by swemoney** [chatty/chatty#340]
**Is your feature request related to a problem? Please describe.**
With the new Channel Points system, users accumulate a currency while watching a stream. This currency can be redeemed for a couple of default things like unlocking emotes but the streamer can also create custom items that the user can purchase. These purchases don't appear in Chatty at all. They do appear in Twitch chat kind of like a highlighted/sub message.

**Describe the solution you'd like**
A notification style message (styleable to make it stand out) that states how many coins a user spent, what item was purchased and any message that's included with it. I haven't found where these purchases are posted if they don't contain a message (one of the options with the purchase is to require that the user includes a message). But when they do contain a message, they have a special tag called "custom-reward-id" with a uuid identifier for that reward.

**Describe alternatives you've considered**
No alternatives as it's a brand new feature on Twitch.

**Comment by tduva** [comment]
Can you give me an example of a channel that has custom rewards?

**Comment by swemoney** [comment]
I have a custom reward in my channel. I can also create an extra small reward for testing.

twitch.tv/swemoney

**Comment by RoboKun** [comment]
twitch.tv/vinesauce also is in the beta for channel points

**Comment by marcmagus** [comment]
Note: custom rewards with a message appear in chatty as a plain message. The feature to make highlight reward messages appear as highlighted has not changed this in any way. Not sure if this additional information is helpful.

**Comment by tduva** [comment]
The message only contains a reward id, but since there is no public API for channel points, it could only display that it is a custom reward, but not what the reward is.

**Comment by swemoney** [comment]
Ya. Sadly, you would have to know the reward-id to know what reward was redeemed. It would be nice to be able to highlight these messages or make them [NOTICE] messages (or both). Otherwise they look just like normal chat and I may not realize an action needs to be taken for this message. It would be REALLY nice if we could display rewards that are redeemed without a chat message, but I haven't found any way to receive these yet aside from the official twitch chat.

**Comment by swemoney** [comment]
I just noticed the new beta with highlight support (sorry about that). Working great. I wonder if it would be possible to pass something like reward-id:safdas-dsa-das-dsa-dsada to the highlighter so (if we know the reward-id) we could highlight specific rewards differently. Perhaps we can even enable the reward-id to display in the message so we can make a test redemption and grab the reward-id for highlighting later?

**Comment by tduva** [comment]
You can match on message tags directly if you're adventurous, e.g. `config:t|custom-reward-id=r3ward-1d` to match a specific reward id or just `config:t|custom-reward-id` to match *all* custom reward messages. To find out the reward id, you could look in "Extra - Debug window - Irc log" (tick "Irc log" at the bottom).

Of course the tag might change without warning, since the feature is still in beta. And I don't know if the reward ids ever change (on their own, or when editing the reward?). But feel free to experiment with it.

**Comment by swemoney** [comment]
That's **exactly** what I was looking for when the highlighted messages first came out. Thanks a bunch for that tip! I'll play around with it for sure.

**Comment by tduva** [comment]
In the next beta, custom rewards will be shown as an info message (this test reward can be triggered by using `/debug simulate creward`):

    23:12 [Points] Test redeemed a custom reward (unknown) [Message text]

Since it's an info message now, the mentioned matching prefixes (e.g. for Highlighting) won't work anymore unless you also add `config:info` (e.g. `config:t|custom-reward-id,info` or `config:t|custom-reward-id config:info`).

I've also added a way to change the `(unknown)` by setting a description manually for a reward id (`/set rewards r3ward-1d Test Reward`), which turns it into:

    23:15 [Points] Test redeemed a custom reward (Test Reward) [Message text]

Now obviously this isn't very user friendly, but since I don't have access to that information through an API and I'm not sure whether/when reward ids can change, I'll leave it at this for the current release version. It can be used for people that want to experiment.

**Comment by kcoderhere** [comment]
I found that this only works if the reward requires a message to be sent with the reward.  If there's no message, the reward redemption message doesn't show up in Chatty (just the Twitch chat window).  How do you get the reward-id for a custom reward?

**Comment by swemoney** [comment]
If the reward doesn't have a message attached, it never gets sent through IRC at all. Twitch doesn't have an API for their channel points so I don't think there's anything we can do about this until we get an API/PubSub for channel point redemption.

**Comment by tduva** [comment]
It's now possible to see more messages/information on your own channel, so the channel of the account you're logged into Chatty with (if you allow additional access under "Main - Login.." and restart). Overall the API is still pretty limited though.
