### ISSUE TITLE
Attempting to Connect to Rooms Causes Chatty to Lose Connection to IRC Server

### ISSUE THREAD

**Issue by Yolopanther12** [chatty/chatty#346]
**Describe the bug**
Connecting to a channel's room(s) causes all open channels in Chatty to lose connection to Twitch IRC. Chatty will attempt to reconnect, however it will not be successful. The re-connection attempts will always stay on the "first" re-connection attempt (e.g. _Attempting to reconnect in 1 seconds.. (1/40)_ ) and never increment meaning Chatty will always only wait 1 second before attempting to reconnect. If you close the tab that is attempting to connect to the room then Chatty will successfully reconnect to Twitch IRC.

**To Reproduce**
1. Connect to any channel that has a room.
2. Connect to the room.
3. See error.

**Expected behavior**
Twitch is [officially closing rooms](https://help.twitch.tv/s/article/rooms-are-closing) on October 30 2019, so ideally the rooms feature in Chatty should no longer be available.

**Additional information**
- OS: Windows 10
- Chatty Version: v0.10 Hotkey, v0.11-b1 standalone (latest beta as of writing this issue)
- Java Version: 1.8.0_201
- When has the issue first occured: October 28 2019
- How often does the issue occur: Every time the reproduction steps are followed

**Additional context**
I was only able to test this with a single channel because it's the only one I could easily find that uses rooms. The channel was **#coestar** and the room was **spoilers**.
Since rooms will be officially closed tomorrow I assume this bug is just the result of the closure process. However, it's been a few weeks since Twitch announced the closure and the latest beta still allows you to attempt to connect to rooms.

**Comment by tduva** [comment]
I didn't see any information on how the removal would be handled. I expected it to just not join the channel, certainly not just disconnect. It's not surprising that it doesn't increments the reconnection counter, because it *does* connect successfully on the first attempt, it just gets reconnected immediately again.

I can add a check that prevents trying to join chatrooms, but anyone who regularly joins chatrooms will probably have already run into the issue before an update. Really Twitch should handle it differently, like just sending a message that the room could not be found.

**Comment by tduva** [comment]
Apparently this was unintentional and has been fixed by Twitch.
