### ISSUE TITLE
Add parameter for mod status in channel for custom commands

### ISSUE THREAD

**Issue by Emilgardis** [chatty/chatty#351]
### The problem
In some channels, I would like to have different commands depending on if I'm a mod or not.

Say I have the following `STimeout` command which timeouts a user via 3rd party bot command `!timeout <user> <seconds...>` when in the `#jtv` channel. 
```
/STimeout#jtv !timeout $$1 $2-
```

This is common in channels where some chatters are so-called "hidden" moderators, no mod badge but can still moderate with bot commands.

This works great, however, if I for whatever reason have been modded in said channel (e.g can now use native `.timeout`), I'd still use the 3rd party solution.

### Solution

Add the `mod` parameter to parameters if user is modded when evaluating the command. For example `//echo $if($(mod),modded,not modded)`.

This would make it possible to do
```
/STimeout#jtv $if($(mod),.timeout $$1 $2-,!timeout $$1 $2-)
```

### Alternatives
- Add another conditional for commands, i.e `/modonlycommand#optionalchannel@ stuff` where `@` means "_only if modded_", these commands would have to be higher in the stack of available commands to evaluate to to make it work.
- Use boolean `ismod` parameter that is **true** if user is modded, **false** if user is not modded.
    - `twitchuser` **is not** modded in `#jtv` -> 
        `//echo $ifeq($(ismod),true,modded,not modded)` returns `not modded`

    - `twitchuser` **is** modded in `#jtv` -> 
        `//echo $ifeq($(ismod),true,modded,not modded)` returns `modded`

**Comment by tduva** [comment]
The next version will contain the following function which will return `true` or an empty string: `$is(<matching rule>)`

The `<matching rule>` follows the Highlight format, so for example `$is(status:b)` will match if the command was executed from e.g. the User Dialog with a message from the broadcaster selected. Since this is about the status of the local user, not the user that sent the message, the Highlight format will now also have the `mystatus:` prefix. So in your case `$if($is(mystatus:m),<modded>,<not modded>)` would work (or `bm` for mod or broadcaster).

This is a bit longer to write, but it allows for all kinds of combinations of user status (plus also matching on e.g. the message text that the command was executed on, not sure how useful that is, but it's pretty much a byproduct of how this is implemented). The added `mystatus:` prefix may also be useful in other cases.

To make it easier to use, could always add a custom identifier, for example: `_m $is(mystatus:bm)` to the Custom Commands List and then you can use `$if($(_m),<modded>,<not modded>)`.

**Comment by tduva** [comment]
This is now in the latest beta.
