### ISSUE TITLE
Channel Points Highlighted Message notification/sound support

### ISSUE THREAD

**Issue by kcoderhere** [chatty/chatty#356]
**Is your feature request related to a problem? Please describe.**
Channel Points allows a user to get their message highlighted.  Chatty displays the message as highlighted when the option is enabled.  However, the "Highlights" notification/sound event (configured in `Settings->Window->Notifications->Events`) doesn't get triggered off a Channel Points highlighted message.

**Describe the solution you'd like**
Have the Channel Points highlighted message trigger the "Highlights" event notification so I can hear a sound when it happens.

**Describe alternatives you've considered**

- Add a checkbox to the "Highlights" event option to "Trigger on Channel Points messages"
- Add a new event type called "Channel Points" to trigger off various Channel Points events such as highlighted messages and other redemptions.

**Comment by kcoderhere** [comment]
Not sure if this is actually considered a bug or not, but it's still occurring in v0.11

**Comment by tduva** [comment]
You are correct with "displays as highlighted", since the setting under "Highlight" says "*Color* messages highlighted by channel points". The tooltip gives the hint to add `config:hl` to the Highlight list for it to become a proper Highlight, which includes being added to "View - Highlights" and being sent to the Notification system as a Highlight.

I admit that this is confusing, but I didn't really want to add separate Chat Color entries just for Messages highlighted by points, but also not make them an actual Highlight since that annoyed people as well.

The reason why there are so few dedicated options for Channel Points is that the API is still very limited, so not much work has gone into it yet beyond the basics. However, I believe everything you want to do is already possible:

* Via the Highlights list, in which case the messages are all send to the Notification system as a Highlight:
  * Add `config:hl` for Messages highlighted by channel points (if you're testing it yourself, make sure that "Check own text for highlights" is checked)
  * Add `config:info start:[Points]` for most other point redemptions
* Via Notifications, in which case you can define different behavior from Highlight Notifications:
  * Add `config:hl` for Messages highlighted by channel points, to a Notification of the Event type "Chat Message" (if you're testing it yourself, make sure that "Own messages as well" is checked)
  * Add `config:info start:[Points]` for most other point redemptions, to a Notification of the Event type "Info Message"

You can also use the same type of matching/selecting messages in other places, such as Msg. Colors settings, the Ignore list and more. `config:info` means it is looking at Info Messages rather than normal Chat Messages and `start:[Point]` is a simple text match (which can also be used for other messages without having to add a dedicated option for each one, for example if you wanted to match on Sub Notifications you could use `config:info start:[Notification]`).

Example for a separate Notification that reacts to other channel point redemptions: 
![points_notification](https://user-images.githubusercontent.com/5621113/72507713-aecfb180-3844-11ea-9ffe-c4077679ab38.png)

On a related note, if this is for your own channel (the account you're logged into Chatty with), also make sure that you have the "Points Redemptions" access ("Main - Login.." / restart after changing it) for more detailed messages.
