### ISSUE TITLE
Patreon button doesnt work.

### ISSUE THREAD

**Issue by rodrigograca31** [chatty/chatty#375]
**Describe the bug**
The "BECOME A PATREON" button doesnt work.

**To Reproduce**
1. Go to [https://chatty.github.io/](https://chatty.github.io/)
2. Click on 'BECOME A PATREON'
3. See error `www.patreon.com refused to connect.`

**Expected behavior**
Open patreon

**Debug Log**
(Chrome)
![image](https://user-images.githubusercontent.com/1134310/82322236-1736c700-99ce-11ea-98fd-3a0a93f7a0d3.png)

**Additional information (please complete the following information):**
- OS: Linux Mint (but doesnt matter)
- Browser: Chrome 84.0.4143.2

**Additional context**
This is because Patreon doesnt allow iframe embedding.
To go around this I think you can just add `target="_blank"` to your `a` tag to open in a new tab.

Now I should get half of your new patreon subs money........... :stuck_out_tongue: 

Also: why are you embeding your own site? seems like a waste... probably to display the names...? isnt a better way of doing it?

Anyways, I wanted to thank you very much for doing such amazing software and making it open source! (I'm using the notification and sound feature to know when someone speaks on my very new channel so that I get notified and talk back to them) (the OS dependant notification didnt work but I wont bother you with that bug....)

**Comment by tduva** [comment]
Thanks for the tip. It wasn't intended to open in the iframe at all. I guess I always just middle-clicked it.

The names are embeded so they can be updated automatically. Otherwise I would have to commit the updates to GitHub manually. Another option would be loading them into the page with with JavaScript, but that won't work for every page visitor.

**Comment by rodrigograca31** [comment]
If you are worried that people dont have JS enabled you are worried about the wrong thing.
They do.

This is a Twitch.com related software and Twitch.com doesnt even work without JS enabled

**Comment by tduva** [comment]
I have JavaScript disabled on all pages by default. I don't know statistics of how many people are using stuff like NoScript or uMatrix, but if something works fine without JavaScript, I'd rather avoid it.

The Patreon button should work by now. I opted for `target="_top"`, which has the originally intended effect (don't open in a new tab, but also not in the iframe).

**Comment by rodrigograca31** [comment]
Side question: can I ask you why do you have JS disabled?
Navigating the web must be painful... :sob:

**Comment by tduva** [comment]
Extensions like NoScript or uMatrix allow enabling scripts per domain, so it's not really that difficult for frequently visited sites that require JS. I just don't want some random site I don't know yet to be able to run JS, since it can do annoying things and can be a potential security/privacy risk. With an Ad-Blocker and one of the various privacy extensions a lot of the annoying or privacy related issues are probably already removed though, so if you don't want to hassle of enabling scripts on new sites when you actually do need them, that's probably enough.

**Comment by rodrigograca31** [comment]
:+1:
