### ISSUE TITLE
Global hotkeys make Chatty crash on jre8u261

### ISSUE THREAD

**Issue by GenesisFR** [chatty/chatty#380]
**Describe the bug**
Setting any hotkey as Global makes Chatty crash when using Java 8 update 261.

**To Reproduce**
1. Go to Settings > Hotkeys.
2. Set any hotkey as Global.
3. Hit Done then Save.
4. Chatty crashes.

**Expected behavior**
Chatty shouldn't crash.

**Debug Log**
I reverted to jre8u251 so I don't have relevant logs anymore. When using jre8u261, there wasn't anything useful pertaining to the crash in there anyway.

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/3614449/87602636-58451200-c6c5-11ea-8372-2dae232ed49f.png)

**Additional information (please complete the following information):**
- OS: Win10 x64 v1909
- Chatty Version: 0.12 64-bit hotkey
- Java Version: jre8u261
- When has the issue first occurred: after updating to jre8u261
- How often does the issue occur: always

**Additional context**
I've been running jre8u251 for months without issues. The problem started appearing last night right after updating to jre8u261.

**Comment by tduva** [comment]
I was able to reproduce the issue. It appears that the JIntellitype.dll is causing issues, so the JRE crashes. I don't think there is anything I can do about that unless the JIntellitype library is updated.

Incidentally I'm in the progress of switching to another library anyway, since JIntellitype was already reported to not work for later Java versions, so I'm probably not going to pursue this much further.

**Comment by GenesisFR** [comment]
No problem, I'll stick to jre8u251 for now. Thanks for looking into it!

**Comment by tduva** [comment]
The latest beta changed the global hotkey library, if you want to test that.

**Comment by GenesisFR** [comment]
Just tried and it works fine with 0.13b1, thanks!
