### ISSUE TITLE
Some GIF emotes don't show up properly

### ISSUE THREAD

**Issue by chatty** [chatty/chatty#4]
Some BTTV emotes like `(ditto)` don't render properly. I have no idea if I can fix it though. I'm not even sure what part in Java doesn't like it.

**Comment by night** [comment]
This might be because Java doesn't support GIFs in the newest format GIF89a, it only supports GIF87a. I've used https://github.com/DhyanB/Open-Imaging to decode incompatible GIFs in the past.

**Comment by tduva** [comment]
Thanks for your suggestion. I tried reading the problematic emotes with the `GifDecoder.java` class, but the frame delay doesn't display correctly.

* For the `Citto` emote ([image](https://cdn.betterttv.net/emote/55cb47a82718127806ad3202/1x)) it shows 0 as delay. I guess in this case I could just assume 0.1s delay.
* For the `(ditto)` emote ([image](https://cdn.betterttv.net/emote/554da1a289d53f2d12781907/1x)) it shows 1 as delay (which means 10ms). It seems like 0.1s would be correct for this one, but I can't really guess that from what it gives me.
* For the `dittoPride` emote ([image](https://cdn.betterttv.net/emote/55e5658fb8729d3a39595832/1x)) it shows 10 as delay (which means 100ms), which seems to be correct. But that one displays in Chatty correctly anyway.

In addition, the last frames of the Citto emote also don't render properly when I retrieve them with `gif.getFrame(i)`. So it seems like exactly those emotes that cause problems in Chatty also don't really work with the `GifDecoder.java` class.

**Comment by tduva** [comment]
I tested several different ways to decode/encode GIFs while correcting for frame delay and each one of them has different problematic emotes working perfectly while some others are screwed up. Seems pretty difficult to reliably display all kinds of different animated GIFs. `GifDecoder.java` seemed to be the best on average and from the few emotes I tested at least a little improvement.

**Comment by night** [comment]
For delay, make sure that you are using the delay set per frame, not just the delay from the first frame to animate the GIF. It is technically possible to have a 0 delay set on a frame, in which case that frame might be skipped entirely.

> In addition, the last frames of the Citto emote also don't render properly when I retrieve them with gif.getFrame(i).

Can you elaborate?

**Comment by tduva** [comment]
But how would I know whether a delay of 0 is intentional or not? It's certainly not intentional to have your CPU at 80% because all frames are at 0 delay.

Some frames simply don't look like the actual emote when read with the `GifDecoder.java`. It works fine with an `ImageReader`, but that fails at other stuff.

**Comment by night** [comment]
> But how would I know whether a delay of 0 is intentional or not? It's certainly not intentional to have your CPU at 80% because all frames are at 0 delay.

If all frames are 0 delay, perhaps the frames are decoded improperly. I'm not particularly well versed in format specification of GIFs, so I couldn't begin to tell you were the code breaks down.

**Comment by tduva** [comment]
All I know is that all different ways of decoding it in Java (built-in and external classes) that I tried resulted the same delays that didn't make much sense (for some of the emotes). When I open the `Citto` emote in Gimp it also shows a 0ms delay on each frame. `(ditto)` shows 10ms which is also too fast (by a factor of 10 it seems). Apparently browsers (as well as probably other programs) usually cap the fps GIFs can be displayed at, so it's possible that whoever made the GIF tested it and it seemed fine, even though he meant to actually make it another delay. But I don't really know much about GIFs either.

**Comment by GhettoGirl** [comment]
Hey, i want to share some thoughts with you guys.
But first: I'm __NOT__ a Java dev, so I can't help with real code.

I see you have a lot of problems rendering GIF images.

So I tried rendering this 3 GIFs in Qt5 using C++ code and all 3 GIFs are totally fine and ok :)
No glitches or bugs

--
I recorded a video of how the GIFs look [here](http://tinypic.com/player.php?v=skzukj%3E&s=9).
And [this](http://code.metager.de/source/xref/lib/qt/src/gui/image/qgifhandler.cpp) is the code Qt uses internally for GIF rendering, it should give you ideas on how to solve the problem. The Qt devs pretty much made their own GIF format renderer; so no official libgif used.

Hope this helps.

**Comment by tduva** [comment]
Thanks, but I don't think I have the time or ability to implement my own GIF decoder right now.

**Comment by GhettoGirl** [comment]
It's me again. I finally got a Java IDE up and running.
Even if I don't know Java, I'll try my best to reimplement the Qt code into Java and help fixing the GIF rendering issue.
When the time has come, I'll make a __pull request__ ;)

Hope this bug gets fixed as soon as possible.

**Comment by tduva** [comment]
You should put it in an own project if you do this, so everyone can use it more easily.

**Comment by GhettoGirl** [comment]
I forked Chatty to my GitHub account. I already started to work on it, since this broken GIF bother me myself.

**Comment by tduva** [comment]
That's not what I meant. I was talking about making the Gif Fix standalone so other Java projects can benefit from it as well.

**Comment by tduva** [comment]
So I've been using https://github.com/DhyanB/Open-Imaging to fix animated GIFs, but it also doesn't work for quite a few of them. Recently I discovered a fork (https://github.com/wsxjump/Open-Imaging) that fixes one type of issue, but broke other GIFs, which I managed to fix myself.

So as it stands it supports a few more GIFs now, but it still fails at some of them, for example the following:
![citto2x](https://cloud.githubusercontent.com/assets/5621113/22398258/1e124956-e585-11e6-84ca-f5de2f00083a.gif)

This is what the individual frames look like when decoded with the [GifDecoder](https://github.com/chatty/chatty/blob/7880b6aa3304624e92897f2e1af4d9549545ad35/src/chatty/util/gif/GifDecoder.java):
![citto2x gif_frames](https://cloud.githubusercontent.com/assets/5621113/22398305/eb9ac100-e585-11e6-976b-3564099e0828.jpg)

Some of the frames look like the pixels are somehow shifted over or something. Since some of the frames are completely garbled I suspect it might have to do the decoding of the actual frame, possibly to do with LZW decoding, but I only have a very rudimentary understanding of that so I couldn't find an obvious error. I also got an `ArrayIndexOutOfBoundsException` when actually outputting the [exception there](https://github.com/chatty/chatty/blob/7880b6aa3304624e92897f2e1af4d9549545ad35/src/chatty/util/gif/GifDecoder.java#L241) (not occuring with any of the GIFs that are decoded ok), which supports the assumption that an error lies in that area. Even if the exception could be normal, it only occuring with broken looking GIFs is suspicious. I couldn't find the original root of the exception though.

**Comment by tduva** [comment]
Changed to another GIF Decoder, which seems to work better.
