### ISSUE TITLE
please change the irc server to irc.chat.twitch.tv

### ISSUE THREAD

**Issue by domoaligato** [chatty/chatty#40]
Twitch is in progress of moving the chat servers to aws and chatty needs to have the server changed to irc.chat.twitch.tv for it to work correctly.

**Comment by craftwar** [comment]
They point to the same ip addresses (After Twitch chat migration)

**Comment by tduva** [comment]
The beta already changes the `serverDefault` and `portDefault` settings, although it doesn't really matter too much since as @craftwar mentioned `irc.twitch.tv` and `irc.chat.twitch.tv` now resolve to the same IPs.

In addition, you can also change those settings yourself in the Settings GUI, if the need for that should arise (just in case that wasn't clear).
