### ISSUE TITLE
Workaround for posting combined Emoji.

### ISSUE THREAD

**Issue by Mm2PL** [chatty/chatty#447]
Check list:
- [x] using newest beta at the time of writing
- [x] link RFC

**Additional context**

I've created an RFC for this: https://gist.github.com/Mm2PL/982c76964fe53f80fcf6b6963bba049f. Rendered LaTeX PDF: https://mm2pl.github.io/emoji_rfc.pdf. This is a workaround for https://github.com/twitchdev/issues/issues/307.

**Is your feature request related to a problem? Please describe.**

Yes, but it's a TMI issue, the chat server removes the **ZERO WIDTH JOINER** character which makes posting and receiving combined emoji (like 👨‍🌾) impossible. They just get turned into their parts, in this case 👨🌾. 

![2021-12-04_20-53](https://user-images.githubusercontent.com/25011746/144722855-b629b2c3-1856-4179-b005-9f7bace1b518.png)

**Describe the solution you'd like**

I'd like for Chatty to replace **U+260D** (ZERO WIDTH JOINER) with **U+E0002** (no official name) when sending/receiving messages as I've described in the RFC.

**Describe alternatives you've considered**

Not doing it and bothering Twitch to fix it and probably having them ignore us.

**Comment by lewisje** [comment]
Your proposed character, although unassigned, is still in a range intended for use in [language-tagging](https://en.m.wikipedia.org/wiki/Plane_\(Unicode\)#Supplementary_Special-purpose_Plane); have you considered using something from a Private Use Area? If not, is it because Twitch already filters those characters out?

**Comment by Mm2PL** [comment]
Twitch filters PUA characters. I actually did think of using another character or duplicated white space as an escape sequence for this, but I against it because of number of characters required for that to work.

**Comment by lewisje** [comment]
I realize that this would be difficult to comprehensively test, but does Twitch even filter out characters from planes 15 and 16? I remembered that the BMP has its own PUA and suspected that that's what you tested.

(It would be disappointing if they even filtered out the 109 Shibuya emoji, which is still exclusively in the BMP PUA because it was rejected as a Unicode emoji, because it represents a trademarked entity.)

**Comment by Mm2PL** [comment]
I tested parts of both BMP and supplemental private area A and B. I just tested the Shibuya 106 emoji. It's filtered.

**Comment by leon-richardt** [comment]
Just a little update, this workaround has now been implemented in Chatterino (https://github.com/Chatterino/chatterino2/pull/3469) and DankChat (https://github.com/flex3r/DankChat/commit/d5303b9f7659b19e18427bc22c56efb44d9f9df9).

**Comment by Felanbird** [comment]
This workaround has been implemented into Chatsen (chatsen/chatsen@0350eb5) as well.

**Comment by Felanbird** [comment]
This workaround has been implemented into FrankerFaceZ. (FrankerFaceZ/FrankerFaceZ@feae6bc)
![image](https://user-images.githubusercontent.com/41973452/153670606-77a5a646-b64b-46d8-8ce4-78b4a644d5d1.png)
