### ISSUE TITLE
Mod Announcements

### ISSUE THREAD

**Issue by deanpcmad** [chatty/chatty#464]
**Is your feature request related to a problem? Please describe.**

Twitch have just added an Announcement feature in chat - https://twitter.com/zachbussey/status/1509563256230359041

When testing, it receives this from IRC (websockets) but it doesn't send a normal IRC message. Here's an example of what it sends:

```
@badge-info=subscriber/60;badges=moderator/1,subscriber/3060,bits/200000;color=#1E90FF;display-name=deanpcmad;emotes=;flags=;id=069e0077-bba2-491f-9b77-bfdb9a89d549;login=deanpcmad;mod=1;msg-id=announcement;msg-param-color=BLUE;room-id=13363719;subscriber=1;system-msg=;tmi-sent-ts=1648761264110;user-id=72938118;user-type=mod :tmi.twitch.tv USERNOTICE #fremily :testing something
```

There are multiple versions of the announce command, which set the colour as it's shown in chat:

![image](https://user-images.githubusercontent.com/425200/161150899-16faa9f0-9b53-4647-99f2-c699fdde3534.png)

**Describe the solution you'd like**

The ability for these messages to be shown like `/me` messages are shown, where the test is coloured and bolded?

**Comment by tduva** [comment]
The message does come through IRC, although it's missing some data that Chatty expects, so it doesn't get output. The latest beta already outputs a very basic version, but improvements are forthcoming. The text won't be colored since that may be difficult to read on some backgrounds, but it will stand out more than a regular message.
