### ISSUE TITLE
Tracking new visitors

### ISSUE THREAD

**Issue by webadequate** [chatty/chatty#79]
Hello.
As I right understand i can to track new visitors through
![image](https://cloud.githubusercontent.com/assets/1946769/18285184/5ca0ea38-7497-11e6-8883-8bf9750b03d5.png)
and I can track obly register watchers.
We have some ways for track unregistered watchers?

**Comment by TrainerTimmy1** [comment]
AFAIK there's no way you can track unregistered watchers. However, if you pay close attention to the title bar, there's a chatter count and viewer count (the former appears first). If there's more viewers than chatters, then it usually means there are more unregistered viewers than registered ones.

And I wouldn't recommend relying on Joins/Parts because they're sent once every minute. A lot of times a a person would send a message before Chatty (or any IRC client that can access Twitch chat) receives a join message. Sometimes it doesn't catch users who disconnect from chat very often, such as people using the Twitch mobile app and frequently switching between other apps.
